CREATE TABLE  ALUNOCP2 (
Cod_aluno INT PRIMARY KEY NOT NULL,
Nome VARCHAR (50), 
Sobrenome VARCHAR (50)
);


CREATE TABLE PROFESSOR (
Cod_professor INT PRIMARY KEY NOT NULL,
Nome VARCHAR (50),
Sobrenome VARCHAR (50)
);

CREATE TABLE USUARIO (
Cod_usuario INT PRIMARY KEY NOT NULL,
Nome VARCHAR (50),
Sobrenome VARCHAR (50)
);

CREATE TABLE CONTEUDO (
Cod_conteudo INT PRIMARY KEY NOT NULL,
Nome VARCHAR (50),
Nivelamento VARCHAR (10),
Comentarios VARCHAR (500),
Avaliacao INT NOT NULL,
Especificar_materia VARCHAR (30), 
);

CREATE TABLE DISCIPLINA (
Cod_disciplina INT PRIMARY KEY NOT NULL,
Nome VARCHAR (50)
);

CREATE TABLE AVALIACAO (
Cod_avaliacao INT PRIMARY KEY NOT NULL
);

CREATE TABLE COMENTARIO (
Cod_comentario INT PRIMARY KEY NOT NULL,
Caracteres VARCHAR (500)
);
